version: '2'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.bun
        environment:
            - ORIGIN=http://localhost:3000
        ports:
            - 3000:3000
        volumes:
            - ./images:/home/bun/app/images
        networks:
            - hermes

    database:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - db:/data/db
        networks:
            - hermes

volumes:
    db:

networks:
    hermes:
